import {
  GlupatoneBC,
  WhiteningEmulsion,
  FacialBeautyCream,
  SkinPolish300g,
  CentellaCream30G,
  goldenPearlMassageCream,
  AcneRemovalCream,
  bioaouaUnderArmCream,
  VitaminCCream60g,
  VitaminCWhiteningCream,
  BiPureAcneCream,
  SaeedGhaniFootAndHandCream,
  dermawickUrgerntFacial,
  DermacosWhiteningSkinPolishBleachSet,
  FairandLovelyCream,
  SeiBella,
  GlowAndCleanSkinPolish,
  HeavenDoveCream,
  GoldenPearlUrgentFacial,
  BioaquaAcneRemoval,
  VitaminECapsuleJar,
  DeepFreshUVCream,
  DeuuHerbalSkinPolish,
  YardlieAntiAcneVitaminC,
  RubellaWhitenningCream,
} from "./Images/exportBCImgs";

import {
  bioaouaUnderArmCreamDetails,
  RubellaWhitenningCreamDesc,
  DeuuHerbalSkinPolishDesc,
  DeepFreshUVCreamDesc,
  VitaminECapsuleJarDesc,
  GlowAndCleanSkinPolishDesc,
  BioaquaAcneRemovalDesc,
  HeavenDoveCreamDesc,
  dermawickUrgerntFacialDesc,
  GoldenPearlUrgentFacialDesc,
  SeiBellaDesc,
  FairandLovelyCreamDesc,
  DermacosWhiteningSkinPolishBleachSetDesc,
  BiPureAcneCreamDesc,
  SaeedGhaniFootAndHandCreamDesc,
  VitaminCCream60gDesc,
  GlupatoneBCDesc,
  FacialBeautyCreamDesc,
  WhiteningEmulsionDesc,
  SkinPolish300gDesc,
  CentellaCream30GDesc,
  VitaminCWhiteningCreamDesc,
  goldenPearlMassageCreamDesc,
  AcneRemovalCreamDesc
} from "./productDescription";

let BrighteningCreamsArr = [
  {
    img: bioaouaUnderArmCream,
    text: "BIOAQUA Nenhong Pink Body Cream Lips Underarm Cream 30gm",
    price: "899/-",
    reducedPrice: "649/-",
    productCode: "MZ72600026BSMCS",
    shortDetail: bioaouaUnderArmCreamDetails,
    rating: "4.0",
  },
  {
    img: RubellaWhitenningCream,
    text: "2 Pcs Whitening Cream Rubella Beauty Range",
    price: "649/-",
    reducedPrice: "499/-",
    productCode: "MZ83100015NANTR",
    shortDetail: RubellaWhitenningCreamDesc,
    rating: "4.0",
  },
  {
    img: YardlieAntiAcneVitaminC,
    text: "Yardlie Professional Vitamin C Beauty Cream",
    price: "689/-",
    reducedPrice: "549/-",
    productCode: "MZ84200076DOSTC",
    shortDetail:
      "Anti Acne, Whitening, Suitable for All Skin Types Product Details:Material: Cream Product Type: Vitamin C Beauty Cream Product Details: Anti Acne, Whitening, Suitable for All Skin Types, Export Quality with SPF45.",
    rating: "4.0",
  },
  {
    img: DeuuHerbalSkinPolish,
    text: "Dew Herbal Expert Ultra Glowing Skin Polish",
    price: "899/-",
    reducedPrice: "599/-",
    productCode: "MZ57300128UDEES",
    shortDetail: DeuuHerbalSkinPolishDesc,
    rating: "4.0",
  },
  {
    img: DeepFreshUVCream,
    text: "Deep Fresh Brightening Cream",
    price: "1099/-",
    reducedPrice: "899/-",
    productCode: "MZ35500121GLABM",
    shortDetail: DeepFreshUVCreamDesc,
    rating: "4.0",
  },
  {
    img: VitaminECapsuleJar,
    text: "Vitamin E Skin Whitening Capsules Jar",
    price: "699/-",
    reducedPrice: "499/-",
    productCode: "MZ88700003ARSML",
    shortDetail: VitaminECapsuleJarDesc,
    rating: "5.0",
  },
  {
    img: GlowAndCleanSkinPolish,
    text: "Glow and Clean Ultra Whitening Skin polish 3 in 1",
    price: "1599/-",
    reducedPrice: "1199/-",
    productCode: "MZ48800055ARUMT",
    shortDetail: GlowAndCleanSkinPolishDesc,
    rating: "5.0",
  },
  {
    img: BioaquaAcneRemoval,
    text: "BIOAQUA Salicylic Acid Acne Removal Cream 20g",
    price: "449/-",
    reducedPrice: "349/-",
    productCode: "MZ59300116FIFEC",
    shortDetail: BioaquaAcneRemovalDesc,
    rating: "5.0",
  },
  {
    img: HeavenDoveCream,
    text: "Heaven Dove Whitening Cream",
    price: "999/-",
    reducedPrice: "749/-",
    productCode: "MZ67400000027CYCH",
    shortDetail: HeavenDoveCreamDesc,
    rating: "4.0",
  },
  {
    img: dermawickUrgerntFacial,
    text: "Whitening And Glowing Urgent Facial",
    price: "699/-",
    reducedPrice: "499/-",
    productCode: "MZ22100017MSEE",
    shortDetail: dermawickUrgerntFacialDesc,
    rating: "5.0",
  },
  {
    img: GoldenPearlUrgentFacial,
    text: "Golden Pearl Unique Formula Whitening Urgent Facial 75ML",
    price: "499/-",
    rating: "4.0",
    reducedPrice: "349/-",
    productCode: "MZ53500000003HHK",
    shortDetail: GoldenPearlUrgentFacialDesc,
  },
  {
    img: SeiBella,
    text: "SeiBella-Skin Glowing Cream",
    price: "799/-",
    rating: "5.0",
    reducedPrice: "649/-",
    productCode: "MZ100700007RTBY",
    shortDetail: SeiBellaDesc,
  },
  {
    img: FairandLovelyCream,
    text: "Fair & Lovely Advanced Multi Vitamin Cream 25ml",
    price: "499/-",
    rating: "5.0",
    reducedPrice: "399/-",
    productCode: "MZ60720008AASGML",
    shortDetail: FairandLovelyCreamDesc,
  },
  {
    img: DermacosWhiteningSkinPolishBleachSet,
    text: "Dermacos Dermapure Skin Polish and Bleach Set Kit, Pack Of 3",
    price: "2199/-",
    reducedPrice: "1549/-",
    productCode: "MZ80120008LABY",
    shortDetail: DermacosWhiteningSkinPolishBleachSetDesc,
  },
  {
    img: BiPureAcneCream,
    text: "Bi Pure Acne Cream",
    price: "849/-",
    reducedPrice: "719/-",
    productCode: "MZ100700011RTBY",
    shortDetail: BiPureAcneCreamDesc,
  },
  {
    img: SaeedGhaniFootAndHandCream,
    text: "Saeed Ghani Foot & Hand Whitening Cream",
    price: "1099/-",
    reducedPrice: "949/-",
    productCode: "MZ23800030SKTS",
    shortDetail: SaeedGhaniFootAndHandCreamDesc,
  },
  {
    img: VitaminCCream60g,
    text: "Bioaqua Vitamin C Moisturizing Hydrating Rejuvenating Facial Cream 50g",
    price: "899/-",
    reducedPrice: "599/-",
    productCode: "MZ726002801BSMCS",
    shortDetail: VitaminCCream60gDesc 
  },
  {
    img: GlupatoneBC,
    text: "Glupatone Skin Whitening Cream",
    price: "749/-",
    reducedPrice: "549/-",
    shortDetail: GlupatoneBCDesc,
    productCode: "MZ60320025MNSRPS",
  },
  {
    img: FacialBeautyCream,
    text: "Homeo Cure Beauty Cream",
    price: "699/-",
    reducedPrice: "499/-",
    shortDetail: FacialBeautyCreamDesc,
    rating: "5.0",
    productCode: "MZ60320024MNSRPS",
  },
  {
    img: WhiteningEmulsion,
    text: "Glupatone Whitening And Brightening Emulsion",
    price: "999/-",
    reducedPrice: "699/-",
    shortDetail: WhiteningEmulsionDesc,
    productCode: "MZ109020208QYCSSE",
  },
  {
    img: SkinPolish300g,
    text: "Whitening Skin Polish 300g",
    price: "999/-",
    reducedPrice: "599/-",
    shortDetail: SkinPolish300gDesc,
    rating: "5.0",
    productCode: "MZ108920020NWSNBY",
  },
  {
    img: CentellaCream30G,
    text: "Skin Ever Centella Soothing Cream 30g",
    price: "899/-",
    reducedPrice: "649/-",
    shortDetail: CentellaCream30GDesc,
    rating: "5.0",
    productCode: "MZ2600085ARCC",
  },
  {
    img: VitaminCWhiteningCream,
    text: "Vitamin C Brightening & Anti Aging Face Cream",
    price: "839/-",
    reducedPrice: "649/-",
    productCode: "MZ726002801BSMCS",
    shortDetail: VitaminCWhiteningCreamDesc,
  },
  {
    img: goldenPearlMassageCream,
    text: "Skin Lightening Massage Cream",
    price: "899/-",
    reducedPrice: "549/-",
    shortDetail: goldenPearlMassageCreamDesc,
    productCode: "MZ66600110GNCS",
  },
  {
    img: AcneRemovalCream,
    text: "BIOAQUA Acne Scar Removal Rejuvenation Cream",
    price: "719/-",
    reducedPrice: "399/-",
    shortDetail: AcneRemovalCreamDesc,
    productCode: "MZ19920097RAAS",
  },
];

BrighteningCreamsArr = BrighteningCreamsArr.map((product) => ({
  ...product, 
  category: "brighteningCreams"
}))

export { BrighteningCreamsArr }